### ISSUE TITLE
Análise de fonte

### ISSUE THREAD

**Issue by LeonardoRios** [robsonrosilva/advpl-sintaxe#13]
Olá, 

Gostaria de saber se seria possível analisar apenas o arquivo atualmente aberto, porque ele analise todos os arquivos do WorkSpace aberto.
Será que seria possível?

**Comment by robsonrosilva** [comment]
Boa tarde,

Desculpe a demora na resposta.

Já fiz essa implementação se adicionar configuração no seu settings:

 "advpl-sintaxe": {
    "validaProjeto": false
  }
