### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rodrigopg** [robsonrosilva/advpl-sintaxe#14]
- Issue Type: `Performance`
- Extension Name: `advpl-sintaxe`
- Extension Version: `0.7.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/rodrigo/robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by rodrigopg** [comment]
[robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt](https://github.com/robsonrosilva/advpl-sintaxe/files/3019845/robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt)

**Comment by robsonrosilva** [comment]
Boa tarde Rodrigo,
Fiz uma implementação para uso de cache, o start na minha máquina reduziu em 50% o processamento.
Favor atualize a extensão e verifique se a ainda á esse problema de performance.
Obrigado por ajudar a melhorar a extensão.

**Comment by robsonrosilva** [comment]
Chegou a testar a performance da nova versão?

**Comment by robsonrosilva** [comment]
@rodrigopg testei durante 1 mês a versão 0.7.8 montei um cache do projeto e após a primeira análise as demais levam 1/6 do tempo em relação a primeira, caso identifique mais algum problema de performance pode reabrir essa issue.
