### ISSUE TITLE
Validar apenas fonte atual

### ISSUE THREAD

**Issue by keinou** [robsonrosilva/advpl-sintaxe#18]
Seria interessante uma forma que fosse possível validar apenas o fonte atual, seja quando aberto ou apenas quando for compila-lo

**Comment by keinou** [comment]
Quando possuimos um projeto muito grande, mas muito grande mesmo, o vscode fica indisponivel para a compilação, debug e outras opções até que a validação seja finalizada.

**Comment by robsonrosilva** [comment]
É possível fazer isso colocando no settings a configuração abaixo:
"validaProjeto": false
Tem um exemplo no readme.md aqui no Github.

**Comment by keinou** [comment]
Quando realizo esta configuração o mesmo não valida nada.

**Comment by robsonrosilva** [comment]
Quando coloca essa configuração ele roda a validação do fonte quando o mesmo é alterado.
Posso colocar para ele validar o fonte quando for aberto, acho que vai atender melhor para as situações que a análise está desativada.
Se eu implementar assim atende sua necessidade?

**Comment by silfar** [comment]
Aproveitando Robson, mesmo alterando o fonte ele não é validado não. acho que sim, na hora de abrir o fonte seria ideal.

**Comment by keinou** [comment]
Aqui ele não valida quando é alterado, quando aberto e quando salvo acho que fica show!

**Comment by robsonrosilva** [comment]
Blz vou implementar assim então.
Na semana que vem devo soltar uma release assim.

**Comment by keinou** [comment]
Show de bola, obrigado, e parabens pelo plugin, é uma otima ferramenta!!!
