### ISSUE TITLE
dúvidas

### ISSUE THREAD

**Issue by silfar** [robsonrosilva/advpl-sintaxe#19]
Olá, estou testando seu pluguin, sugiram algumas duvidas:
Como usa o modelo de comentario comentFontPad?
Epoderia descrevre para que serve as seguintes configurações:
			"empresas": ["01", "02"],
			"ownerDb": ["PROTHEUS", "PROTHEUS12"].

abraços.

**Comment by robsonrosilva** [comment]
Os dois utilizo para validação de queryes.
"empresas" por exemplo critica se montar uma query e deixar fixa a tabela "SA1010" por exemplo e existir a configuração de empresas com a "01" ele vai criticar dizendo que a empresa foi fixada na query e deve se utilizar ou %table:SA1% ou RetSqlName("SA1").
"ownerDb" por exemplo critica se montar uma query e deixar fixo o banco de dados pois em alguns lugares que trabalhei montávamos as queryes com o nome do banco, mas na hora de colocar no ADVPL esquecíamos de remover o nome do banco e gera problema lógico.
"comentFontPad" ele deve ser montado com padrão de JSON, ou seja no exemplo que coloquei deixei o padrão de comentário de fontes que gosto de usar, ai ele já critica para ver se o fonte está seguindo esse padrão de comentário no seu começo(valida as primeiras linhas do fonte):

/*//##########################################################
Projeto : EMPRESA
Modulo  : SIGAGPE
Fonte   : NOME DO FONTE
Objetivo: o que meu fonte faz
*///##########################################################


`
"comentFontPad": [
	"/*//##########################################################",
	"Projeto\\ \\:",
	"Modulo\\ \\ \\:",
	"Fonte\\ \\ \\ \\:",
	"Objetivo\\:"
]`

**Comment by silfar** [comment]
Robson, tem algum exemplo de como configurar os branches ?

**Comment by silfar** [comment]
Robson, tem algum exemplo de como configurar os branches ?

**Comment by silfar** [comment]
Robson, tem algum exemplo de como configurar os branches ?

**Comment by robsonrosilva** [comment]
No arquivo readme aqui no projeto tem um exemplo com todas as configurações, mas em resumo só basta definir os nomes das branches que serão utilizadas para validação, homologação e produção.
Tem um exemplo nele de como serão feitos os merges nas branches.
Para esse tipo de fluxo sempre trabalhamos com uma branch onde desenvolvemos e com as 3 branches recebendo as alterações dessa branch de desenvolvimento.

**Comment by marcelohoc** [comment]
Robson, tentei seguir seu modelo de comentário, copiei e colei as linhas que citou nesta Issue e mesmo assim continua falando que a função não foi comentada. Tem algum exemplo do settings e de um comment que não apresente como não comentado para testar?

**Comment by robsonrosilva** [comment]
O comentário de funções não tem relação com o settings.json, identifico o comentário de acordo com o padrão de comentários ProtheusDoc. Achei que estava falando do comentário de fontes.

Portanto se você colocar o nome da função após /*/{Protheus.doc} conforme o exemplo a baixo ele para de criticar.

#INCLUDE "TOTVS.ch"

//------------------------------------------------------------------------------------------
/*/{Protheus.doc}PMCFGM01
Descrição

@version   1.00
@since 12/03/14
/*/
//------------------------------------------------------------------------------------------

User Function PMCFGM01(cAssunto, cBody, cTo, cCc, cBcc, cAnexo)
	Local oProcess := TWFProcess():New( "000000", "Envios em geral" )

	oProcess :NewTask( cAssunto, "\workflow\padrao.htm" )

	oProcess:oHTML:ValByName( "corpo" , cBody)

	oProcess:cSubject 	:= cAssunto
	oProcess:cTo		:= cTo
	oProcess:cCC		:= cCc
        oProcess:cBcc      	:= cBcc
	oProcess:AttachFile(cAnexo)
	oProcess:Start() // Inicia o processo com o Messenger ativo gera o HTML na pasta do usuário pelo messenger.

	WFSendMail({cEmpAnt,cFilAnt})
Return

`

**Comment by marcelohoc** [comment]
> O comentário de funções não tem relação com o settings.json, identifico o comentário de acordo com o padrão de comentários ProtheusDoc. Achei que estava falando do comentário de fontes.
> 
> Portanto se você colocar o nome da função após /*/{Protheus.doc} conforme o exemplo a baixo ele para de criticar.
> 
> #INCLUDE "TOTVS.ch"
> 
> //------------------------------------------------------------------------------------------
> /*/{Protheus.doc}PMCFGM01
> Descrição
> 
> @Version 1.00
> @SInCE 12/03/14
> /*/
> //------------------------------------------------------------------------------------------
> 
> User Function PMCFGM01(cAssunto, cBody, cTo, cCc, cBcc, cAnexo)
> Local oProcess := TWFProcess():New( "000000", "Envios em geral" )
> 
> ```
> oProcess :NewTask( cAssunto, "\workflow\padrao.htm" )
> 
> oProcess:oHTML:ValByName( "corpo" , cBody)
> 
> oProcess:cSubject 	:= cAssunto
> oProcess:cTo		:= cTo
> oProcess:cCC		:= cCc
>     oProcess:cBcc      	:= cBcc
> oProcess:AttachFile(cAnexo)
> oProcess:Start() // Inicia o processo com o Messenger ativo gera o HTML na pasta do usuário pelo messenger.
> 
> WFSendMail({cEmpAnt,cFilAnt})
> ```
> 
> Return
> 
> `

**Comment by marcelohoc** [comment]
Muito obrigado Robson.
