### ISSUE TITLE
Quando instalado Advpl-sintaxe Servers buga e nao aparece mais e extensao parou de funcionar

### ISSUE THREAD

**Issue by josealbertoo** [robsonrosilva/advpl-sintaxe#21]
Quando instalado Advpl-sintaxe TOTVS Developer Studio Code buga (servers) e nao aparece mais e extensão parou de funcionar. Removendo extensão Advpl-sintaxe TOTVS Developer Studio Code volta ao normal... isso aconteceu sexta pra ca...

**Comment by robsonrosilva** [comment]
Estranho não publiquei nada essa semana, se puder abra o inspetor de objetos(Ajuda->Alternar Ferramentas do  Desenvolvedor) em seguia instale a extensão e verifica se vai aparecer alguma coisa no console do inspetor de objetos.

**Comment by josealbertoo** [comment]
abstractExtensionService.ts:396 [totvs-healthcare.totvs-healthcare-dev]: Linguagem desconhecida em `contributes.totvs-healthcare-dev.language`. Valor fornecido: abl
_logMessageInConsole @ abstractExtensionService.ts:396
_handleExtensionPointMessage @ abstractExtensionService.ts:347
n @ abstractExtensionService.ts:323
_msg @ extensionsRegistry.ts:37
error @ extensionsRegistry.ts:46
e.toValidSnippet @ snippetsService.ts:62
y.point.setHandler.e @ snippetsService.ts:214
_handle @ extensionsRegistry.ts:142
acceptUsers @ extensionsRegistry.ts:133
_handleExtensionPoint @ abstractExtensionService.ts:382
_doHandleExtensionPoints @ abstractExtensionService.ts:328
_rehandleExtensionPoints @ extensionService.ts:236
_deltaExtensions @ extensionService.ts:223
async function (async)
_deltaExtensions @ extensionService.ts:180
_handleDeltaExtensions @ extensionService.ts:160
B._register._extensionManagementService.onDidInstallExtension.e @ extensionService.ts:119
fire @ event.ts:580
e.listener.e.event.e @ event.ts:744
fire @ event.ts:580
e @ event.ts:55
fire @ event.ts:580
fire @ event.ts:582
handlers.set.e @ ipc.ts:557
onResponse @ ipc.ts:618
onBuffer @ ipc.ts:604
protocolListener.protocol.onMessage.e @ ipc.ts:449
fire @ event.ts:580
_register._socketReader.onMessage.e @ ipc.net.ts:368
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
dom.ts:215 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
f @ dom.ts:215
v @ dom.ts:236
_setListeningToMouseWheel @ scrollableElement.ts:320
b @ scrollableElement.ts:219
_ @ scrollableElement.ts:491
w @ listView.ts:241
H @ listWidget.ts:1199
z @ listService.ts:259
_createInstance @ instantiationService.ts:117
createInstance @ instantiationService.ts:82
createNotificationsList @ notificationsList.ts:73
show @ notificationsList.ts:49
addToast @ notificationsToasts.ts:173
onDidNotificationChange @ notificationsToasts.ts:112
_register.model.onDidNotificationChange.e @ notificationsToasts.ts:92
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:509
a @ event.ts:55
onFirstListenerAdd @ event.ts:113
_event._event @ event.ts:509
O @ listWidget.ts:544
createMouseController @ listWidget.ts:1251
H @ listWidget.ts:1238
z @ listService.ts:259
_createInstance @ instantiationService.ts:117
createInstance @ instantiationService.ts:82
createNotificationsList @ notificationsList.ts:73
show @ notificationsList.ts:49
addToast @ notificationsToasts.ts:173
onDidNotificationChange @ notificationsToasts.ts:112
_register.model.onDidNotificationChange.e @ notificationsToasts.ts:92
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
extensionHost.ts:204 Extension Host
extensionHost.ts:205 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
extensionHost.ts:204 Extension Host
extensionHost.ts:205  1: 00007FF7139476CF 
 2: 00007FF7125DCA46 
 3: 00007FF7125DCC56 
 4: 00007FF7117C3828 
 5: 00007FF7117C37C9 
 6: 00007FF71183C110 
 7: 00007FF711844569 
 8: 00007FF7114603F9 
 9: 00007FF7114FE577 
10: 00007FF71161C950 
11: 00007FF711A2FDF2 
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  134  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
_onExtensionHostCrashed @ extensionService.ts:375
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:147
e.onDidExit @ abstractExtensionService.ts:137
fire @ event.ts:580
_onExtHostProcessExit @ extensionHost.ts:467
_extensionHostProcess.on @ extensionHost.ts:219
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240
notificationsAlerts.ts:40 Host de extensão foi encerrado inesperadamente.
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
prompt @ notificationService.ts:165
_onExtensionHostCrashed @ extensionService.ts:395
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:147
e.onDidExit @ abstractExtensionService.ts:137
fire @ event.ts:580
_onExtHostProcessExit @ extensionHost.ts:467
_extensionHostProcess.on @ extensionHost.ts:219
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240
dom.ts:215 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
f @ dom.ts:215
v @ dom.ts:236
_setListeningToMouseWheel @ scrollableElement.ts:320
b @ scrollableElement.ts:219
_ @ scrollableElement.ts:491
w @ listView.ts:241
H @ listWidget.ts:1199
z @ listService.ts:259
_createInstance @ instantiationService.ts:117
createInstance @ instantiationService.ts:82
createNotificationsList @ notificationsList.ts:73
show @ notificationsList.ts:49
addToast @ notificationsToasts.ts:173
onDidNotificationChange @ notificationsToasts.ts:112
_register.model.onDidNotificationChange.e @ notificationsToasts.ts:92
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
prompt @ notificationService.ts:165
_onExtensionHostCrashed @ extensionService.ts:395
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:147
e.onDidExit @ abstractExtensionService.ts:137
fire @ event.ts:580
_onExtHostProcessExit @ extensionHost.ts:467
_extensionHostProcess.on @ extensionHost.ts:219
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:19
_event._event @ event.ts:509
a @ event.ts:55
onFirstListenerAdd @ event.ts:113
_event._event @ event.ts:509
O @ listWidget.ts:544
createMouseController @ listWidget.ts:1251
H @ listWidget.ts:1238
z @ listService.ts:259
_createInstance @ instantiationService.ts:117
createInstance @ instantiationService.ts:82
createNotificationsList @ notificationsList.ts:73
show @ notificationsList.ts:49
addToast @ notificationsToasts.ts:173
onDidNotificationChange @ notificationsToasts.ts:112
_register.model.onDidNotificationChange.e @ notificationsToasts.ts:92
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
prompt @ notificationService.ts:165
_onExtensionHostCrashed @ extensionService.ts:395
_onExtensionHostCrashOrExit @ abstractExtensionService.ts:147
e.onDidExit @ abstractExtensionService.ts:137
fire @ event.ts:580
_onExtHostProcessExit @ extensionHost.ts:467
_extensionHostProcess.on @ extensionHost.ts:219
emit @ events.js:182
ChildProcess._handle.onexit @ internal/child_process.js:240

**Comment by josealbertoo** [comment]
Problema resolvido!!

Refiz minha workspace e reconfigurei...

Deu certinho
