### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jtjunior2** [robsonrosilva/advpl-sintaxe#22]
- Issue Type: `Performance`
- Extension Name: `advpl-sintaxe`
- Extension Version: `1.0.7`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\jtjun\robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt
[robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt](https://github.com/robsonrosilva/advpl-sintaxe/files/4118639/robsonrosilva.advpl-sintaxe-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robsonrosilva** [comment]
Bom dia, favor atualize a extensão para verificar se o consumo de CPU melhora, já alterei algumas coisas para tentar melhorar.
Vou deixar essa issue aberta, pois ainda tenho algumas melhorias para fazer no analisador de códigos.
Caso esteja prefira hyá uma configuração no settings que desabilita a análise do projeto assim só é processada a análise dos fontes abertos.
Obrigado por ajudar a melhorar a extensão.

**Comment by robsonrosilva** [comment]
Boa tarde, Verifique se a versão que publiquei hoje gera uma melhora de performance no seu projeto, melhorei algumas expressões regex que nos computadores que uso geraram uma melhoria de 20% na performance da análise.

**Comment by jtjunior2** [comment]
Bom Dia Robson,

fiz a atualização é sim, carregou bem mais rapido o plugin.

abrigado pelo retorno.


att
João


Em qui., 6 de fev. de 2020 às 13:31, Robson Rogério Silva <
notifications@github.com> escreveu:

**Comment by robsonrosilva** [comment]
Obrigado por ajudar a melhorar a extensão.
