### ISSUE TITLE
É recomendado o uso da expressão CRLF

### ISSUE THREAD

**Issue by leonardoap** [robsonrosilva/advpl-sintaxe#24]
Qual a tratativa recomendada pra esse caso?

![image](https://user-images.githubusercontent.com/16844067/85299339-86935100-b47b-11ea-8870-86fa51abe58c.png)

**Comment by robsonrosilva** [comment]
Bom dia nesse caso a recomendação é adicionar o include TOTVS.CH.
Esse include cria uma variável ESTÁTICA no FONTE com o nome CRLF, então tendo o INCLUDE TOTVS.CH você pode só usar a CRLF.
