### ISSUE TITLE
Extensão aponta erro no código porém SonarQube/CodeAnalysis não

### ISSUE THREAD

**Issue by Redschenko** [robsonrosilva/advpl-sintaxe#25]
Boa tarde

A extensão está apresento erro para fontes que estão usando dbUseArea()
![Screenshot_154](https://user-images.githubusercontent.com/21147378/90914758-c95aa200-e3b4-11ea-832d-5fe15e8d0bcd.png)

Porém, ao submeter o fonte para o SonarQube/CodeAnalysis, não está indicando erro.
![Screenshot_155](https://user-images.githubusercontent.com/21147378/90914832-ea22f780-e3b4-11ea-995f-3602a0bfc393.png)

Por que está apontando erro para dbUseArea()

At
Rodrigo de Oliveira

**Comment by robsonrosilva** [comment]
Boa tarde estou implementando uma correção sairá ne próxima versão a correção.

**Comment by Redschenko** [comment]
> Boa tarde estou implementando uma correção sairá ne próxima versão a correção.

Obrigado @robsonrosilva pela atenção.
Apenas para meu acompanhamento, você tem previsão de quando será liberada a próxima versão?

**Comment by robsonrosilva** [comment]
Devo usar um tempinho aqui a versão beta, em geral uso durante uma semana antes de publicar. Se quiser posso te enviar um prévia dele.

**Comment by Redschenko** [comment]
> Devo usar um tempinho aqui a versão beta, em geral uso durante uma semana antes de publicar. Se quiser posso te enviar um prévia dele.

Sim. Pode me enviar que eu também faço testes durante uma semana e te reporto.

**Comment by robsonrosilva** [comment]
Segue a versão beta.
O arquivo vsix tem que ser extraído e pode ser instalado no vscode.

Segue um link que explica como instalar https://qastack.com.br/programming/37071388/how-can-i-install-visual-studio-code-extensions-offline.

[advpl-sintaxe-1.2.3.zip](https://github.com/robsonrosilva/advpl-sintaxe/files/5371756/advpl-sintaxe-1.2.3.zip)
