### ISSUE TITLE
Aponta como erro quando utiliza a palavra "Copy to "

### ISSUE THREAD

**Issue by Redschenko** [robsonrosilva/advpl-sintaxe#26]
Bom dia.

Quando utilizo uma variável tipo caractere e atribuo o texto "Copy to ", a extensão indica erro: _Chamada descontinuada de Driver ISAM. Use a API FWTemporaryTable._

Isto ocorre somente se o texto tiver espaço.
Veja a imagem.

![Screenshot_179](https://user-images.githubusercontent.com/21147378/94811781-3a39a480-03cc-11eb-8abf-2f986a53e780.png)

At
Rodrigo de Oliveira

**Comment by robsonrosilva** [comment]
Boa tarde estou implementando uma correção sairá ne próxima versão a correção.

**Comment by Redschenko** [comment]
> Boa tarde estou implementando uma correção sairá ne próxima versão a correção.

Obrigado @robsonrosilva pela atenção.
Apenas para meu acompanhamento, você tem previsão de quando será liberada a próxima versão?
